name: Publish to PyPI

on:
  release:
    types:
      - published  # Trigger when a release is published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # Use your preferred Python version

    # Step 3: Install Poetry
    - name: Install Poetry
      run: |
        pip install poetry

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        poetry install --no-root

    # Step 5: Build the package
    - name: Build the package
      run: |
        poetry build

    # Step 6: Publish to PyPI
    - name: Publish to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry config pypi-token.pypi $PYPI_API_TOKEN
        poetry publish --build