name: Build and Publish to PyPI

on:
  push:
    branches:
      - main # Run build job on push/merge to main
  release:
    types:
      - published # Trigger publish job only when a release is published

jobs:
  # Step 1: Build Job (Runs on Push to Main)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Ensure latest version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 # Use your preferred Python version

      - name: Install Poetry
        run: pip install poetry>=2.0.0

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build the package
        run: poetry build

      - name: Upload built package
        uses: actions/upload-artifact@v4 # ✅ Upgrade to v4
        with:
          name: dist-files
          path: dist/
          retention-days: 7 # Keep for 7 days

  # Step 2: Publish Job (Runs on Release Event)
  publish:
    needs: build # Ensure build completes first
    runs-on: ubuntu-latest
    if: github.event_name == 'release' # Only run on release event
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built package
        uses: actions/download-artifact@v4 # ✅ Upgrade to v4
        with:
          name: dist-files
          path: dist/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 # Use your preferred Python version

      - name: Install Poetry
        run: pip install poetry>=2.0.0

      - name: Publish to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_API_TOKEN
          poetry publish --build
